### ISSUE TITLE
Translations

### ISSUE THREAD

**Issue by splitt3r** [ChristophWurst/nextcloud_vue#2]
Is the Nc translation script still able to crawl the translatable strings? I´m using a [Mixin](https://github.com/splitt3r/mindmaps/blob/feature/rework-js/js/Mixins.ts) for the translations but i think the problem will be the same. Is it possible to easily update the perl script?

**Comment by ChristophWurst** [comment]
Take a look at the mail app. We use Handlebars and a special php script that extracts template translations into a format the perl script understands. It's in the ’build‘ dir IIRC.

**Comment by splitt3r** [comment]
Thanks for the hint. I will have a look at it.
